export * from '../../common'
export * from './CheckPhoneNumber'
export * from './GetCallCount'
export * from './GetRecord'
export * from './GetRecordUrl'
export { getConfig, getKintoneRestAPIClient, setConfig } from '../../common'
export { appId } from '../desktop'
